//! What differs between the protocol versions this codec speaks.
//!
//! One codec serves every release from 1.21.11 on. Each release is a
//! [`Version`]: its packet ids (by name, from the game's own `packets.json`),
//! the tables that translate the engine's ids into its own, how it receives
//! its registries, and a [`Gen`] for the handful of places where a packet's
//! *layout* changed rather than its id. The tables are generated by
//! `tools/gen/versions.py`; the layout differences are written out in the
//! codec, each with the release that introduced it.

use aether_world::BlockStateId;

use crate::protocol::nbt::Nbt;

/// Packet ids of one version, by phase, direction and vanilla name; `-1`
/// where the version has no such packet. Field list: `tools/gen/packet_fields.txt`.
#[derive(Debug)]
// Generated for every packet in the field list, including a few the codec
// matches by other means.
#[allow(dead_code)]
pub struct Packets {
    pub cb_add_entity: i32,
    pub cb_animate: i32,
    pub cb_swing_animation: i32,
    pub cb_block_changed_ack: i32,
    pub cb_block_destruction: i32,
    pub cb_block_update: i32,
    pub cb_level_chunk_with_light: i32,
    pub cb_forget_level_chunk: i32,
    pub cb_set_chunk_cache_center: i32,
    pub cb_container_close: i32,
    pub cb_container_set_content: i32,
    pub cb_container_set_data: i32,
    pub cb_damage_event: i32,
    pub cb_entity_event: i32,
    pub cb_entity_position_sync: i32,
    pub cb_explode: i32,
    pub cb_game_event: i32,
    pub cb_level_event: i32,
    pub cb_open_screen: i32,
    pub cb_player_abilities: i32,
    pub cb_player_combat_kill: i32,
    pub cb_player_position: i32,
    pub cb_respawn: i32,
    pub cb_rotate_head: i32,
    pub cb_set_entity_data: i32,
    pub cb_set_entity_motion: i32,
    pub cb_set_equipment: i32,
    pub cb_set_experience: i32,
    pub cb_set_health: i32,
    pub cb_set_held_slot: i32,
    pub cb_set_time: i32,
    pub cb_sound: i32,
    pub cb_take_item_entity: i32,
    pub cb_keep_alive: i32,
    pub cb_login: i32,
    pub cb_player_info_update: i32,
    pub cb_player_info_remove: i32,
    pub cb_remove_entities: i32,
    pub cb_system_chat: i32,
    pub cb_commands: i32,
    pub sb_accept_teleportation: i32,
    pub sb_chat_command: i32,
    pub sb_chat_command_signed: i32,
    pub sb_chat: i32,
    pub sb_client_command: i32,
    pub sb_container_click: i32,
    pub sb_container_close: i32,
    pub sb_interact: i32,
    pub sb_attack: i32,
    pub sb_punch: i32,
    pub sb_pick_item_from_block: i32,
    pub sb_player_command: i32,
    pub sb_player_input: i32,
    pub sb_player_action: i32,
    pub sb_set_carried_item: i32,
    pub sb_set_creative_mode_slot: i32,
    pub sb_swing: i32,
    pub sb_use_item_on: i32,
    pub sb_use_item: i32,
    pub sb_move_player_pos: i32,
    pub sb_move_player_pos_rot: i32,
    pub sb_move_player_rot: i32,
    pub sb_move_player_status_only: i32,
    pub sb_change_game_mode: i32,
    pub sb_keep_alive: i32,
    pub cfg_cb_finish_configuration: i32,
    pub cfg_cb_registry_data: i32,
    pub cfg_cb_resource_pack_push: i32,
    pub cfg_cb_select_known_packs: i32,
    pub cfg_cb_update_tags: i32,
    pub cfg_sb_finish_configuration: i32,
    pub cfg_sb_select_known_packs: i32,
    pub login_cb_login_finished: i32,
    pub login_sb_hello: i32,
    pub login_sb_login_acknowledged: i32,
}

/// The generations of the modern protocol, oldest first.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
pub enum Gen {
    /// 1.21.11 (protocol 774).
    V1_21_11,
    /// 26.1 – 26.1.2 (775): world clocks replace the time-of-day field;
    /// `interact` loses its attack mode to a packet of its own; chunk
    /// sections carry a fluid count; registries grow sound variants, world
    /// clocks and timelines.
    V26_1,
    /// 26.2 (776): the login packet gains `online_mode`, login-finished a
    /// session id, and the registries a sulfur-cube archetype.
    V26_2,
    /// 26.3 (777): game modes go as VarInts with an optional previous one;
    /// position sync carries a path rather than a delta; arm swings get a
    /// packet of their own; explosions say whether to play their sound.
    V26_3,
}

/// How a version receives its synchronized registries.
pub enum Registries {
    /// Every entry with its data, built by the server (1.21.11).
    Explicit,
    /// Entries named only, the client filling them from its own
    /// `minecraft:core` pack — confirmed through "select known packs" —
    /// except the overworld dimension type, whose height is the server's.
    KnownPacks {
        core: &'static [&'static str],
        synced: &'static [(&'static str, &'static [&'static str])],
        overworld: fn() -> Nbt,
        /// Every entry of `synced` with its data, for a client without the
        /// pack: length-prefixed network NBT, deflated.
        data: &'static [u8],
    },
}

/// One protocol version.
pub struct Version {
    pub name: &'static str,
    /// The protocol id announced in the handshake.
    pub protocol: i32,
    pub gen: Gen,
    pub packets: &'static Packets,
    /// Runs of `(first engine state, length, first version state)`.
    pub state_runs: &'static [(u32, u32, u32)],
    /// Block states in this version, for the direct palette's width.
    pub state_count: u32,
    pub items: &'static [(&'static str, u16)],
    pub entity_types: &'static [(&'static str, u16)],
    pub menu_chest: i32,
    pub menu_double_chest: i32,
    pub menu_crafting: i32,
    pub menu_furnace: i32,
    pub component_damage: i32,
    pub component_custom_name: i32,
    pub particle_explosion: i32,
    pub particle_explosion_emitter: i32,
    pub registries: Registries,
    pub tags: &'static [(&'static str, &'static [(&'static str, &'static [u32])])],
}

impl Version {
    /// This version's id for an engine block state.
    pub fn state(&self, id: BlockStateId) -> u32 {
        let raw = id.raw();
        let i = self
            .state_runs
            .partition_point(|(start, _, _)| *start <= raw);
        match i.checked_sub(1).map(|i| self.state_runs[i]) {
            Some((start, len, to)) if raw < start + len => to + (raw - start),
            // Not an engine state at all: stone, rather than an id the
            // client would reject.
            _ => self.state(aether_world::registry::ids::STONE),
        }
    }

    /// Bits per entry of a direct block palette.
    pub fn direct_bits(&self) -> u8 {
        (32 - (self.state_count - 1).leading_zeros()) as u8
    }

    /// This version's id for an item, by name.
    pub fn item_id(&self, name: &str) -> Option<i32> {
        self.items
            .binary_search_by(|(n, _)| (*n).cmp(name))
            .ok()
            .map(|i| self.items[i].1 as i32)
    }

    /// The name of an item id.
    pub fn item_name(&self, id: i32) -> Option<&'static str> {
        self.items
            .iter()
            .find(|(_, i)| *i as i32 == id)
            .map(|(n, _)| *n)
    }

    /// This version's id for an entity type.
    pub fn entity_type(&self, name: &str) -> Option<i32> {
        self.entity_types
            .binary_search_by(|(n, _)| (*n).cmp(name))
            .ok()
            .map(|i| self.entity_types[i].1 as i32)
    }

    /// The entries of a synchronized registry, in the order they are sent.
    fn synced(&self, registry: &str) -> Option<&'static [&'static str]> {
        match &self.registries {
            Registries::KnownPacks { synced, .. } => {
                synced.iter().find(|(r, _)| *r == registry).map(|(_, e)| *e)
            }
            Registries::Explicit => None,
        }
    }

    /// The network id of a biome.
    pub fn biome(&self, name: &str) -> u32 {
        match self.synced("minecraft:worldgen/biome") {
            Some(list) => list
                .iter()
                .position(|b| *b == name)
                .or_else(|| list.iter().position(|b| *b == "minecraft:plains"))
                .unwrap_or(0) as u32,
            None => super::registry::biome_index(name),
        }
    }

    /// How many biomes the client knows, for the direct biome palette.
    pub fn biome_count(&self) -> u32 {
        match self.synced("minecraft:worldgen/biome") {
            Some(list) => list.len() as u32,
            None => super::chunk::BIOME_REGISTRY_SIZE,
        }
    }

    /// The network id of a damage type.
    pub fn damage_type(&self, name: &str) -> Option<usize> {
        match self.synced("minecraft:damage_type") {
            Some(list) => list.iter().position(|d| *d == name),
            None => super::registry::damage_type_index(name),
        }
    }

    /// The network id of an entry of a synchronized registry.
    pub fn synced_index(&self, registry: &str, name: &str) -> Option<usize> {
        self.synced(registry)?.iter().position(|e| *e == name)
    }
}

macro_rules! version {
    ($name:literal, $proto:literal, $gen:expr, $m:ident, $reg:expr) => {
        Version {
            name: $name,
            protocol: $proto,
            gen: $gen,
            packets: &super::gen::$m::PACKETS,
            state_runs: super::gen::$m::STATE_RUNS,
            state_count: super::gen::$m::STATE_COUNT,
            items: super::gen::$m::ITEMS,
            entity_types: super::gen::$m::ENTITY_TYPES,
            menu_chest: super::gen::$m::MENU_GENERIC_9X3,
            menu_double_chest: super::gen::$m::MENU_GENERIC_9X6,
            menu_crafting: super::gen::$m::MENU_CRAFTING,
            menu_furnace: super::gen::$m::MENU_FURNACE,
            component_damage: super::gen::$m::COMPONENT_DAMAGE,
            component_custom_name: super::gen::$m::COMPONENT_CUSTOM_NAME,
            particle_explosion: super::gen::$m::PARTICLE_EXPLOSION,
            particle_explosion_emitter: super::gen::$m::PARTICLE_EXPLOSION_EMITTER,
            registries: $reg,
            tags: super::gen::$m::TAGS,
        }
    };
}

macro_rules! known_packs {
    ($m:ident) => {
        Registries::KnownPacks {
            core: super::gen::$m::CORE_PACKS,
            synced: super::gen::$m::SYNCED,
            overworld: super::gen::$m::overworld,
            data: super::gen::$m::REGISTRY_DATA,
        }
    };
}

pub static V1_21_11: Version = version!(
    "1.21.11",
    774,
    Gen::V1_21_11,
    v1_21_11,
    Registries::Explicit
);
pub static V26_1: Version = version!("26.1.x", 775, Gen::V26_1, v26_1, known_packs!(v26_1));
pub static V26_2: Version = version!("26.2", 776, Gen::V26_2, v26_2, known_packs!(v26_2));
pub static V26_3: Version = version!("26.3", 777, Gen::V26_3, v26_3, known_packs!(v26_3));

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_1_21_11_tables_are_the_identity_on_engine_states() {
        for raw in [0u32, 1, 86, 279, 29_670] {
            assert_eq!(V1_21_11.state(BlockStateId(raw)), raw);
        }
        assert_eq!(V1_21_11.direct_bits(), 15);
    }

    #[test]
    fn newer_versions_remap_every_engine_state_by_name() {
        for v in [&V26_1, &V26_2, &V26_3] {
            for raw in (0..aether_world::registry::blocks::STATE_COUNT as u32).step_by(997) {
                let ours = aether_world::registry::props::state_name(raw).unwrap();
                let theirs = v.state(BlockStateId(raw));
                assert!(theirs < v.state_count, "{} {ours} -> {theirs}", v.name);
            }
            assert_eq!(v.state(BlockStateId(0)), 0, "air stays air");
        }
        assert_eq!(V26_3.direct_bits(), 16, "26.3 has more than 32768 states");
    }

    #[test]
    fn packet_ids_come_from_the_versions_own_table() {
        assert_eq!(V1_21_11.packets.cb_level_chunk_with_light, 0x2C);
        assert_eq!(V1_21_11.packets.sb_move_player_pos, 0x1D);
        assert_eq!(V26_1.packets.cb_level_chunk_with_light, 45);
        assert_eq!(V26_1.packets.sb_attack, 1);
        assert_eq!(V26_3.packets.sb_swing, -1);
        assert!(V26_3.packets.sb_punch > 0);
    }

    #[test]
    fn the_built_in_registry_data_has_one_tag_per_entry() {
        for v in [&V26_1, &V26_2, &V26_3] {
            let Registries::KnownPacks { synced, data, .. } = &v.registries else {
                panic!("{} sends registries by known pack", v.name);
            };
            let raw = miniz_oxide::inflate::decompress_to_vec_zlib(data).unwrap();
            let (mut at, mut n) = (0usize, 0usize);
            while at < raw.len() {
                let len = u32::from_be_bytes(raw[at..at + 4].try_into().unwrap()) as usize;
                // Mostly compounds; a block transformer is a list.
                assert!(
                    (1..=12).contains(&raw[at + 4]),
                    "{}: entry {n} is a tag",
                    v.name
                );
                at += 4 + len;
                n += 1;
            }
            assert_eq!(at, raw.len());
            let want: usize = synced.iter().map(|(_, e)| e.len()).sum();
            assert_eq!(n, want, "{}", v.name);
        }
    }

    #[test]
    fn items_and_entities_resolve_in_every_version() {
        for v in [&V1_21_11, &V26_1, &V26_2, &V26_3] {
            assert!(v.item_id("minecraft:diamond_sword").is_some(), "{}", v.name);
            assert!(v.entity_type("minecraft:zombie").is_some(), "{}", v.name);
            assert_eq!(
                v.biome("minecraft:plains"),
                v.biome("minecraft:no_such_biome")
            );
        }
    }
}
