//! Groundwork for generating terrain that matches modern vanilla for a given
//! seed, rather than merely resembling it.
//!
//! Separate from [`crate::beta`], which reproduces the *old* generator: the
//! two share nothing but the idea. Vanilla since 1.18 draws from
//! xoroshiro128++ ([`random`]) and shapes terrain with a data-driven graph of
//! density functions whose definitions live in the game's own files, not here.
//!
//! # Status
//!
//! Parity is a measurement, not a claim. Every number below was taken against
//! a reference generated by the game itself — either a world a vanilla server
//! wrote, or the game's own classes driven directly from a copy of the server
//! jar and asked what *they* compute.
//!
//! | layer | state | measured agreement |
//! |-------|-------|--------------------|
//! | [`random`] — xoroshiro128++ and its seeding | done | draw-for-draw against the game's `XoroshiroRandomSource` |
//! | [`noise`] — improved / octave / normal / blended noise | done | bit-identical to the game's `NormalNoise` and `BlendedNoise` |
//! | [`density`] — the data-driven function graph | done | 300 000 / 300 000 values bit-identical across all 15 router entries, 20 000 positions (plus 120 000 / 120 000 on a second seed) |
//! | [`climate`] — multi-noise sampler and biome table | done | 80 000 / 80 000 biome lookups against the game's own biome source; 2 709 504 / 2 709 504 biome cells across 1 764 chunks of a vanilla-generated world |
//! | [`density`] cell interpolation | done | 768 000 / 768 000 interpolated densities bit-identical across 2 000 columns |
//! | [`aquifer`] — fluid choice and stone barriers | done | see below |
//! | [`ore_veins`] | done | see below |
//! | [`generator`] — engine sub-chunks from all of it | done | — |
//! | [`biome_table`] — `OverworldBiomeBuilder` ported to code | done | row-for-row equal to the game's `biome_parameters` report |
//! | [`surface`] — surface rule tree, incl. `temperature`/`steep`/`hole`/bandlands | done | 100% of blocks on 6 chunks, 99.9998% on 40, against the game's surface stage |
//! | [`carver`] — cave, canyon, extra-underground cave | done | same as surface, against the game's carver stage |
//! | [`feature`] — placed features (ores, trees, plants, lakes, springs…) | vanilla-like | 99.7% of all blocks and 96.7% of top blocks against a vanilla server world (plains); not position-exact |
//!
//! The noise stage as a whole — interpolation, aquifers and ore veins together,
//! compared block by block against the game's own output:
//!
//! * against `getBaseColumn`: **768 000 / 768 000** blocks over 2 000 columns
//!   (seed 42) and **384 000 / 384 000** over 1 000 columns on a second seed,
//!   every column identical top to bottom;
//! * against the real chunk fill — the game's `doFill` loop driven over a
//!   4×4-cell `NoiseChunk`, which exercises slice swapping and one aquifer
//!   shared by all 256 columns: **1 179 648 / 1 179 648** blocks over 12
//!   chunks.
//!
//! The second of those matters because one aquifer cut-off is derived from the
//! whole chunk rather than from the column, so a column-at-a-time check could
//! not have caught a chunk-scoping mistake.
//!
//! So: **biomes match vanilla exactly, and so does the noise stage that shapes
//! the terrain.** [`generator::VanillaGenerator`] turns that into engine
//! sub-chunks.
//!
//! On top of that sit the surface rules, the carvers and the decoration step.
//! Surface and carvers are ports checked stage by stage against the game's
//! own `NoiseBasedChunkGenerator` driven over a `ProtoChunk`. Decoration is
//! data-driven from the pack's placed and configured features with the
//! game's seeding (`setDecorationSeed` / `setFeatureSeed`) and feature order;
//! it is vanilla-like rather than exact, because vanilla's own result depends
//! on the order in which neighbouring chunks were decorated. Not generated:
//! structures, geodes, dungeons, fossils, dripstone, sculk, desert wells.
//!
//! ## The one place parity is ambiguous
//!
//! Vanilla's biome search keeps a per-thread memory of its previous answer and
//! uses it to settle exact distance ties, so a handful of cells depend on what
//! that thread looked up before — something no outside observer can reconstruct
//! in general. Replaying a cache in fill order reproduces a vanilla-generated
//! world exactly (100 % of 2 709 504 cells); the order-independent lookup
//! differs on 0.03 % of cells, every one of them an exact tie. See
//! [`climate::SearchCache`].
//!
//! ## Reproducing the measurements
//!
//! Three examples, each of which reads the operator's own copy of the game and
//! prints a count:
//!
//! * `vanilla_router_parity` — every density function against a dump from the
//!   game's `NoiseRouter`.
//! * `vanilla_biome_source_parity` — biome selection against a dump from the
//!   game's `MultiNoiseBiomeSource`.
//! * `vanilla_biome_parity` — biomes against the region files of a world a
//!   vanilla server generated.
//! * `vanilla_terrain_parity` — the noise stage against a column dump from the
//!   game, block by block, plus the interpolated density bit for bit.
//!
//! `tests/vanilla_parity.rs` runs the world-based biome check and the terrain
//! check under `cargo test` when the `AETHER_VANILLA_*` environment variables
//! point at the data, and skips quietly when they do not.
//!
//! # Why the game's files
//!
//! Noise settings, biome parameters and surface rules are content, not
//! algorithm. They are read at run time from a copy of the game the operator
//! already has, and deliberately not vendored into this repository.

// Ports of Java loops read better index-for-index, and the float literals
// are the game's own constants, spelled as the game spells them.
#![allow(
    clippy::needless_range_loop,
    clippy::excessive_precision,
    clippy::int_plus_one,
    clippy::manual_range_contains,
    clippy::collapsible_if,
    clippy::assertions_on_constants,
    clippy::items_after_test_module,
    clippy::too_many_arguments,
    clippy::type_complexity
)]

pub mod aquifer;
pub mod biome;
pub mod biome_manager;
pub mod biome_table;
pub mod blockinfo;
pub mod carver;
pub mod chunk;
pub mod climate;
pub mod density;
pub mod feature;
pub mod generator;
pub mod json;
pub mod mth;
pub mod noise;
pub mod ore_veins;
pub mod overworld;
pub mod providers;
pub mod random;
pub mod rng;
pub mod simplex;
pub mod surface;
pub mod tags;
pub mod terrain;

/// A small, fast, non-cryptographic hasher for the generator's position-keyed
/// memo tables (FxHash's multiply-rotate). The default SipHash showed up as a
/// tenth of terrain generation time.
#[derive(Default, Clone, Copy)]
pub struct FxHasher(u64);

impl std::hash::Hasher for FxHasher {
    #[inline]
    fn finish(&self) -> u64 {
        self.0
    }
    #[inline]
    fn write(&mut self, bytes: &[u8]) {
        for b in bytes {
            self.write_u64(*b as u64);
        }
    }
    #[inline]
    fn write_u32(&mut self, v: u32) {
        self.write_u64(v as u64);
    }
    #[inline]
    fn write_i32(&mut self, v: i32) {
        self.write_u64(v as u32 as u64);
    }
    #[inline]
    fn write_u64(&mut self, v: u64) {
        self.0 = (self.0.rotate_left(5) ^ v).wrapping_mul(0x517c_c1b7_2722_0a95);
    }
    #[inline]
    fn write_usize(&mut self, v: usize) {
        self.write_u64(v as u64);
    }
}

/// A `HashMap` keyed with [`FxHasher`].
pub type FxHashMap<K, V> = std::collections::HashMap<K, V, std::hash::BuildHasherDefault<FxHasher>>;
