//! Append-only history of everything that changed the world, and the rollback
//! built on top of it.
//!
//! # The model
//!
//! The world on disk is **not** a copy of the world in memory. It is:
//!
//! ```text
//! world = generator(seed)          the baseline, recomputed on demand
//!       + journal                  every change anyone ever made
//! ```
//!
//! The generator is deterministic, so an untouched column costs nothing to
//! store — it is regenerated byte-for-byte whenever it is needed. Only the
//! changes are written down. A world where a hundred players walked around and
//! placed a hundred blocks stores a hundred entries, not a hundred megabytes of
//! terrain.
//!
//! Each [`Event`] carries both sides of its change, so the log runs in both
//! directions: forwards to rebuild the current state, backwards to undo. That
//! is the whole of the rollback.
//!
//! # Keys
//!
//! Three key spaces share one backend, distinguished by a leading byte, and all
//! three end in a big-endian sequence number so byte order *is* chronological
//! order:
//!
//! ```text
//! 'E' seq(8)                       -> the encoded event
//! 'X' cx(4) cz(4) seq(8)           -> empty; "column cx,cz was touched at seq"
//! 'P' actor(16) seq(8)             -> empty; "this actor acted at seq"
//! 'H'                              -> the high-water sequence number
//! ```
//!
//! The two index spaces hold no payload: they exist so that "what happened in
//! this column" and "what did this player do" are prefix scans rather than a
//! walk of the entire history. Storing the payload once and pointing at it
//! twice also means an event can never disagree with itself.
//!
//! # What a rollback is
//!
//! [`Journal::plan_rollback`] selects events by actor, by area and by time, and
//! returns the block changes that undo them **newest first**. Applying them in
//! that order is what makes overlapping edits come out right: if a player put
//! stone over dirt and then diamond over the stone, undoing newest-first
//! restores stone and then dirt. Undoing oldest-first would leave the diamond.
//!
//! The undo is itself recorded as new events, attributed to whoever ordered it.
//! History is never rewritten — that is the difference between a rollback and
//! a deletion, and it is why a rollback can itself be rolled back.

pub mod event;
pub mod ledger;
pub mod sink;

#[cfg(test)]
mod tests;

pub use event::{ActorId, DecodeError, Event, EventBody, ItemUid, Place};
pub use ledger::{Anomaly, Ledger};
pub use sink::{BatchConfig, BatchingSink, EventSink, SinkStats};

use crate::storage::{KvBackend, StorageError};
use crate::BlockStateId;
use std::sync::atomic::{AtomicU64, Ordering};

const K_EVENT: u8 = b'E';
const K_COLUMN: u8 = b'X';
const K_ACTOR: u8 = b'P';
/// Key holding the high-water sequence number, so a restart does not reuse
/// sequence numbers and silently overwrite history.
const K_HEAD: &[u8] = b"H";

fn event_key(seq: u64) -> [u8; 9] {
    let mut k = [0u8; 9];
    k[0] = K_EVENT;
    k[1..].copy_from_slice(&seq.to_be_bytes());
    k
}

fn column_prefix(cx: i32, cz: i32) -> [u8; 9] {
    let mut k = [0u8; 9];
    k[0] = K_COLUMN;
    // Biased to unsigned so that byte order matches numeric order for negative
    // coordinates too. Without the bias, column -1 would sort above column 1
    // and a prefix scan would still work (it is an exact-match prefix), but the
    // ordering guarantee is cheap and stops the next reader from wondering.
    k[1..5].copy_from_slice(&(cx as u32 ^ 0x8000_0000).to_be_bytes());
    k[5..9].copy_from_slice(&(cz as u32 ^ 0x8000_0000).to_be_bytes());
    k
}

fn column_key(cx: i32, cz: i32, seq: u64) -> [u8; 17] {
    let mut k = [0u8; 17];
    k[..9].copy_from_slice(&column_prefix(cx, cz));
    k[9..].copy_from_slice(&seq.to_be_bytes());
    k
}

fn actor_prefix(actor: ActorId) -> [u8; 17] {
    let mut k = [0u8; 17];
    k[0] = K_ACTOR;
    k[1..].copy_from_slice(&actor.0.to_be_bytes());
    k
}

fn actor_key(actor: ActorId, seq: u64) -> [u8; 25] {
    let mut k = [0u8; 25];
    k[..17].copy_from_slice(&actor_prefix(actor));
    k[17..].copy_from_slice(&seq.to_be_bytes());
    k
}

/// Which events a rollback should undo.
///
/// The three restrictions are independent and combine with AND: an empty
/// filter selects the whole history, which is what "roll back everything"
/// means.
#[derive(Debug, Clone, Default)]
pub struct Filter {
    /// Only this player's actions. `None` selects every actor.
    pub actor: Option<ActorId>,
    /// Only within `radius` blocks of `(x, y, z)`, measured horizontally so
    /// that "clear this area" reaches from bedrock to sky as a player expects.
    pub area: Option<(i32, i32, i32, u32)>,
    /// Only events at or after this sequence number.
    pub since_seq: u64,
    /// Only events at or after this wall-clock time (Unix milliseconds).
    pub since_ms: u64,
}

impl Filter {
    /// Everything, from the beginning of the world.
    pub fn everything() -> Self {
        Self::default()
    }
    /// Restrict to one actor.
    pub fn by(mut self, actor: ActorId) -> Self {
        self.actor = Some(actor);
        self
    }
    /// Restrict to a horizontal radius around a point.
    pub fn near(mut self, x: i32, y: i32, z: i32, radius: u32) -> Self {
        self.area = Some((x, y, z, radius));
        self
    }
    /// Restrict to events no older than `ms`.
    pub fn since_time(mut self, ms: u64) -> Self {
        self.since_ms = ms;
        self
    }

    /// Whether `e` is selected.
    fn matches(&self, e: &Event) -> bool {
        if let Some(a) = self.actor {
            if e.actor != a {
                return false;
            }
        }
        if e.seq < self.since_seq || e.at_ms < self.since_ms {
            return false;
        }
        if let Some((cx, _cy, cz, r)) = self.area {
            let Some((x, _y, z)) = e.position() else {
                // Positionless events (an item moving between two inventory
                // slots) belong to no area, so an area-restricted rollback
                // leaves them alone rather than guessing.
                return false;
            };
            let (dx, dz) = ((x - cx) as i64, (z - cz) as i64);
            let r = r as i64;
            if dx * dx + dz * dz > r * r {
                return false;
            }
        }
        true
    }
}

/// One block restoration produced by a rollback plan.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Restore {
    pub x: i32,
    pub y: i32,
    pub z: i32,
    /// The state to put back.
    pub block: BlockStateId,
    /// The state the rollback is taking away — what the undone edit *placed*.
    ///
    /// This, not the world's current content, is what a recovery stash is owed:
    /// if someone has since built on top of the thing being undone, the
    /// current block belongs to them and handing it over would duplicate it.
    pub removed: BlockStateId,
    /// The sequence number of the event being undone, for the record.
    pub undoing: u64,
}

/// The append-only log over a KV backend.
pub struct Journal<B: KvBackend> {
    backend: B,
    next_seq: AtomicU64,
    /// Optional mirror into an external database. See [`sink`].
    sink: Option<BatchingSink>,
}

impl<B: KvBackend> Journal<B> {
    /// Open a journal on `backend`, continuing its sequence numbering.
    pub fn open(backend: B) -> Result<Self, StorageError> {
        let next = match backend.get(K_HEAD)? {
            Some(v) if v.len() == 8 => u64::from_be_bytes(v.try_into().unwrap()) + 1,
            // No head, or a head we cannot read: fall back to the highest
            // event actually present. Resuming below an existing event would
            // overwrite history, which is the one thing this layer must not do.
            _ => backend
                .scan_prefix(&[K_EVENT])?
                .last()
                .map(|(k, _)| u64::from_be_bytes(k[1..9].try_into().unwrap()) + 1)
                .unwrap_or(1),
        };
        Ok(Self {
            backend,
            next_seq: AtomicU64::new(next),
            sink: None,
        })
    }

    /// Mirror every appended event into `sink` as well.
    ///
    /// The mirror is derived, never authoritative: a journal with no sink
    /// behaves identically, and one whose sink is failing loses nothing that
    /// matters. See the [`sink`] module for why that is the design.
    pub fn with_sink(mut self, sink: BatchingSink) -> Self {
        self.sink = Some(sink);
        self
    }

    /// What the mirror has managed to do, if there is one.
    pub fn sink_stats(&self) -> Option<&SinkStats> {
        self.sink.as_ref().map(|s| s.stats())
    }

    /// Borrow the backend (for flushing alongside the world's own store).
    pub fn backend(&self) -> &B {
        &self.backend
    }

    /// The sequence number the next append will receive.
    pub fn head(&self) -> u64 {
        self.next_seq.load(Ordering::SeqCst)
    }

    /// Append `body` by `actor`, stamped now. Returns the assigned sequence
    /// number.
    pub fn append(&self, actor: ActorId, body: EventBody) -> Result<u64, StorageError> {
        self.append_at(actor, body, now_ms())
    }

    /// [`Journal::append`] with an explicit timestamp, so tests do not depend
    /// on the clock.
    pub fn append_at(
        &self,
        actor: ActorId,
        body: EventBody,
        at_ms: u64,
    ) -> Result<u64, StorageError> {
        self.append_full(actor, body, None, at_ms)
    }

    /// Append an event that happened because of event `cause` — a drop out of
    /// the block break that produced it.
    pub fn append_caused(
        &self,
        actor: ActorId,
        body: EventBody,
        cause: Option<u64>,
    ) -> Result<u64, StorageError> {
        self.append_full(actor, body, cause, now_ms())
    }

    fn append_full(
        &self,
        actor: ActorId,
        body: EventBody,
        cause: Option<u64>,
        at_ms: u64,
    ) -> Result<u64, StorageError> {
        let seq = self.next_seq.fetch_add(1, Ordering::SeqCst);
        let e = Event {
            seq,
            at_ms,
            actor,
            cause,
            body,
        };
        // The payload goes down before either index, so a crash between writes
        // can leave an event nothing points at (harmless: it is skipped) but
        // never an index entry pointing at nothing (which would read as
        // corruption).
        self.backend.put(&event_key(seq), &e.encode())?;
        if let Some((x, _, z)) = e.position() {
            self.backend.put(&column_key(x >> 4, z >> 4, seq), &[])?;
        }
        self.backend.put(&actor_key(actor, seq), &[])?;
        self.backend.put(K_HEAD, &seq.to_be_bytes())?;
        // After the durable write, never before: the mirror must not be able
        // to show an event the journal does not have.
        if let Some(sink) = &self.sink {
            sink.submit(&e);
        }
        Ok(seq)
    }

    /// Read one event by sequence number.
    pub fn get(&self, seq: u64) -> Result<Option<Event>, StorageError> {
        match self.backend.get(&event_key(seq))? {
            Some(blob) => Event::decode(&blob)
                .map(Some)
                .map_err(|e| StorageError::Codec(e.to_string())),
            None => Ok(None),
        }
    }

    /// Every event affecting column `(cx, cz)`, oldest first.
    ///
    /// This is the read the world does when it materializes a column: generate
    /// the baseline, then replay these over it.
    pub fn column_events(&self, cx: i32, cz: i32) -> Result<Vec<Event>, StorageError> {
        self.column_events_from(cx, cz, 0)
    }

    /// The events affecting column `(cx, cz)` numbered `from` or later,
    /// oldest first — the tail after a checkpoint. Earlier events are skipped
    /// on their index key alone, without being read.
    pub fn column_events_from(
        &self,
        cx: i32,
        cz: i32,
        from: u64,
    ) -> Result<Vec<Event>, StorageError> {
        let mut out = Vec::new();
        for (k, _) in self.backend.scan_prefix(&column_prefix(cx, cz))? {
            let seq = u64::from_be_bytes(k[9..17].try_into().unwrap());
            if seq < from {
                continue;
            }
            if let Some(e) = self.get(seq)? {
                out.push(e);
            }
        }
        Ok(out)
    }

    /// The most recent change to the block at `(x, y, z)`, if anyone has ever
    /// touched it.
    ///
    /// `None` means the block is exactly as the generator made it — which is
    /// the question a survival server has to answer before paying for it, or
    /// a player places a diamond block, breaks it, and is paid for the
    /// privilege.
    pub fn last_change_at(&self, x: i32, y: i32, z: i32) -> Result<Option<Event>, StorageError> {
        // Walks the column index backwards and stops at the first hit, so the
        // cost is the number of edits *after* the last one at this position
        // rather than the column's whole history.
        let keys = self.backend.scan_prefix(&column_prefix(x >> 4, z >> 4))?;
        for (k, _) in keys.iter().rev() {
            let seq = u64::from_be_bytes(k[9..17].try_into().unwrap());
            let Some(e) = self.get(seq)? else { continue };
            if e.position() == Some((x, y, z)) {
                return Ok(Some(e));
            }
        }
        Ok(None)
    }

    /// Every event by `actor`, oldest first.
    pub fn actor_events(&self, actor: ActorId) -> Result<Vec<Event>, StorageError> {
        let mut out = Vec::new();
        for (k, _) in self.backend.scan_prefix(&actor_prefix(actor))? {
            let seq = u64::from_be_bytes(k[17..25].try_into().unwrap());
            if let Some(e) = self.get(seq)? {
                out.push(e);
            }
        }
        Ok(out)
    }

    /// The whole history, oldest first. For tooling and the item ledger.
    pub fn all_events(&self) -> Result<Vec<Event>, StorageError> {
        let mut out = Vec::new();
        for (_, v) in self.backend.scan_prefix(&[K_EVENT])? {
            if let Ok(e) = Event::decode(&v) {
                out.push(e);
            }
        }
        Ok(out)
    }

    /// The block changes that undo everything `filter` selects, **newest
    /// first**.
    ///
    /// Applying them in the returned order is required, not merely tidy: two
    /// edits to the same block only unwind correctly from the top of the
    /// stack down.
    ///
    /// Scans the actor index when the filter names one, so a per-player
    /// rollback costs that player's history rather than the world's.
    pub fn plan_rollback(&self, filter: &Filter) -> Result<Vec<Restore>, StorageError> {
        self.plan_rollback_where(filter, &|_| true)
    }

    /// [`Journal::plan_rollback`] with an extra predicate applied after the
    /// filter — for conditions no index can narrow, such as a block name.
    pub fn plan_rollback_where(
        &self,
        filter: &Filter,
        accept: &dyn Fn(&Event) -> bool,
    ) -> Result<Vec<Restore>, StorageError> {
        let candidates = match filter.actor {
            Some(a) => self.actor_events(a)?,
            None => self.all_events()?,
        };
        let selected: Vec<Restore> = candidates
            .iter()
            .rev()
            .filter(|e| filter.matches(e) && accept(e))
            .filter_map(|e| match &e.body {
                EventBody::BlockSet { x, y, z, from, to } => Some(Restore {
                    x: *x,
                    y: *y,
                    z: *z,
                    block: *from,
                    removed: *to,
                    undoing: e.seq,
                }),
                _ => None,
            })
            .collect();

        // A position touched several times collapses to one restoration, and
        // the two halves of it come from opposite ends of the walk:
        //
        // * `block` — what to put back — is the **oldest** selected `from`,
        //   the state before the first edit being undone. Taking the newest
        //   would restore the block to a state it held midway through, which
        //   is the classic off-by-one in a rollback and stays invisible until
        //   two people edit the same block.
        // * `removed` — what the undo takes away, and therefore what the
        //   recovery stash is owed — is the **newest** selected `to`, the last
        //   thing the filter's subject actually put there.
        //
        // The walk is newest-first, so the first sighting of a position gives
        // `removed` and the last gives `block`.
        let mut index: std::collections::HashMap<(i32, i32, i32), usize> =
            std::collections::HashMap::new();
        let mut plan: Vec<Restore> = Vec::new();
        for r in selected {
            match index.get(&(r.x, r.y, r.z)) {
                Some(&i) => {
                    // Older than what we have: it wins the restore target.
                    plan[i].block = r.block;
                    plan[i].undoing = r.undoing;
                }
                None => {
                    index.insert((r.x, r.y, r.z), plan.len());
                    plan.push(r);
                }
            }
        }
        Ok(plan)
    }
}

/// Milliseconds since the Unix epoch, or 0 if the clock is before it.
pub fn now_ms() -> u64 {
    std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_millis() as u64)
        .unwrap_or(0)
}
